### PR TITLE
Fix typo in layout option

### PR DESCRIPTION
**Pull request by syberon**
Form view helper has typo in layout option name: 'twb-layout' instead of 'twbs-layout' which used in other files.

### CODE REVIEW

**Comment by syberon** [comment]
Please make a delay to merge this request. This fix has revealed another bug.

**Comment by syberon** [comment]
Okay, now totally fixed this bug.

**Comment by syberon** [comment]
Hi.
Did you forgot to merge my PRs ? :)

**Comment by neilime** [comment]
Sorry this PR has fallen through the cracks, now it is merged, thank you

**Pull request merged**
