### PR TITLE
Custom attributes to 'form', 'fieldset' and 'form-group' wrapper

### PR DESCRIPTION
**Pull request by syberon**
Allow using of custom attributes in 'form', 'fieldset' tags. Also added ability to add custom attributes to form groups.

### CODE REVIEW

**Comment by neilime** [comment]
@syberon can you fix lint issues. Some phpunit tests will be usefull for this new feature.

Thank you

**Comment by syberon** [comment]
> @syberon can you fix lint issues. Some phpunit tests will be usefull for this new feature.
> 
> Thank you

Unfortunately i can't write the tests.
What lint issues i need to fix?

**Comment by neilime** [comment]
@syberon please check de CI failed logs : https://travis-ci.org/neilime/zf-twbs-helper-module/jobs/613821459

**Comment by syberon** [comment]
I has fixed all issues.

**Pull request merged**
